### ISSUE TITLE
Mobile examples are not building

### ISSUE THREAD

**Issue by mkotsbak** [chandu0101/sri#12]
It fails on some missing npm modules like webpack and graphql declared in package.json in subdirectories. It should be buildable out of the box.

**Comment by chandu0101** [comment]
if you're referring to relay-mobile-examples then you must need graphQL and webpack because relay uses those to generate/validate relay-graphql queries in compile time.

**_Edit :**_ 

ah fullOptMobile compiles relay-mobile-examples too https://github.com/chandu0101/sri/blob/master/project/Build.scala#L117 :( , may be i'll create a new task for relay-mobile-examples -  fullOptRelayMobile

**Comment by chandu0101** [comment]
fixed in #17 ,sorry for the inconvenience :(
